"$Revision:$"!
Delta fileInFromFile: (FilePath for: 'AlienClassTest.dlt') !
Delta fileInFromFile: (FilePath for: 'AlienFalseTest.dlt') !
Delta fileInFromFile: (FilePath for: 'AlienFunctionTest.dlt') !
Delta fileInFromFile: (FilePath for: 'AlienLibraryTest.dlt') !
Delta fileInFromFile: (FilePath for: 'AlienStringTest.dlt') !
Delta fileInFromFile: (FilePath for: 'AlienTest.dlt') !
Delta fileInFromFile: (FilePath for: 'AlienTrueTest.dlt') !
Delta fileInFromFile: (FilePath for: 'CallbackTest.dlt') !
Delta fileInFromFile: (FilePath for: 'DirectAlienTest.dlt') !
Delta fileInFromFile: (FilePath for: 'FFICallbackReturnValueTest.dlt') !
Delta fileInFromFile: (FilePath for: 'IndirectAlienTest.dlt') !
Delta fileInFromFile: (FilePath for: 'PointerAlienTest.dlt') !
Delta fileInFromFile: (FilePath for: 'TestAlien.dlt') !
Delta fileInFromFile: (FilePath for: 'TestInvokeArgs.dlt') !
Delta fileInFromFile: (FilePath for: 'UndefinedObjectTest.dlt') !
