"$Revision:$"!
Delta fileInFromFile: (FilePath for: 'ObjectiveCAlien.dlt') !
Delta fileInFromFile: (FilePath for: 'ObjectiveCObject.dlt') !
Delta fileInFromFile: (FilePath for: 'ObjectiveCClass.dlt') !
Delta fileInFromFile: (FilePath for: 'ObjectiveCClassAlien.dlt') !
Delta fileInFromFile: (FilePath for: 'ObjectiveCMArgs.dlt') !
Delta fileInFromFile: (FilePath for: 'ObjectiveCMethod.dlt') !
Delta fileInFromFile: (FilePath for: 'ObjectiveCSmalltalkObjectProxy.dlt') !
