#!/bin/sh -f
export DeltaDir=`pwd`
tools/primDefFilter.pl > prims.src
./strongtalk-main.exe -f tools/strongtalkrc-forinterpretedtests -script tools/primGen.dlt
sed -i "s/\r//g" prims.inc
mv prims.inc vm/prims
rm prims.src
